/*import { Authprovider } from "@/context/AuthContext";
import Navbar from "@/components/Navbar";
import "./globals.css";





export const metadata = {
  title: "Divisional Secretariat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Authprovider>

      <Navbar/>
        {children}
        </Authprovider>
      </body>
      
    </html>
  );
}*/

import { AuthProvider } from "@/context/AuthContext"; // ✅ Correct casing
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Divisional Secretariat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider> {/* ✅ Correct usage */}
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}




